# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-12 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='start',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projects',
            name='top',
            field=models.BooleanField(default=False),
        ),
    ]
