# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-14 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamma', '0005_auto_20170914_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
