# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-15 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamma', '0006_auto_20170914_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesSecond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('photo', models.FileField(upload_to='')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamma.Services')),
            ],
        ),
    ]
