# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-17 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamma', '0007_servicessecond'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='project',
        ),
        migrations.AddField(
            model_name='gallery',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='top',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imagegallery',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamma.Gallery'),
        ),
    ]
