# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-01 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamma', '0009_gallery_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='top',
        ),
        migrations.AddField(
            model_name='gallery',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
