# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-01 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamma', '0010_auto_20171001_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagegallery',
            old_name='photo',
            new_name='gimg',
        ),
        migrations.AddField(
            model_name='gallery',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
